name: Service Status Check

on:
  schedule:
    - cron: "1,25,55 * * * *"

  # æ·»åŠ æ‰‹åŠ¨è§¦å‘äº‹ä»¶
  workflow_dispatch:

jobs:
  service-check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Check service status
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # æ–°ä»»åŠ¡æŒ‚èµ·
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Run Shell Script
        id: shell_script_run
        run: |
          chmod +x ./checkshell/servicecheck.sh
          bash ./checkshell/servicecheck.sh

      - name: Commit and push changes
        run: |
          git config --local user.name 'Github Actions'
          git config --local user.email 'source@comic.com'
          git add -A --force ./logs/
          git commit -m 'ğŸ†™ [Automated] Update service status logs'
          git push origin master
